version: "3.2"
services:
  api-php-engajamento:
    container_name: api-php-engajamento
    image: api-php-engajamento:7.4-fpm
    build:
      context: api
      dockerfile: Dockerfile
    volumes:
      - ./api/:/var/www/html
      - ./api/docker/php/config/extensions.ini:/usr/local/etc/php/conf.d/extensions.ini
    environment:
      - UPDATE_COMPOSER_DEPENDENCIES=true
      - USE_PHP_FPM=true
      - HOME_URI_VAL=http://localhost
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=123456
      - DB_HOST=database-engajamento
      - DB_PORT=5432
      - DB_CONNECTION=pgsql
    ports:
      - 8081:80
    working_dir: /var/www/html/
    networks:
      - network-engajamento
  nginx-webserver-engajamento:
    container_name: nginx-webserver-engajamento
    image: nginx:1.17-alpine
    volumes:
      - ./api/:/var/www/html/
      - ./api/docker/nginx/backend/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:80"
    depends_on:
      - api-php-engajamento
    networks:
      - network-engajamento
  db-engajamento:
    container_name: db-engajamento
    image: postgres:9.6
    ports:
      - "5433:5432"
    expose:
      - "5432"
    volumes:
      - ./database/docker-data/postgres:/var/lib/postgresql/data
      - ./database/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=laravel
    networks:
      - network-engajamento
networks:
  network-engajamento:
    driver: bridge
